### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by jdunlap** [jburrell7/REUPlusC2#1]
In the list of changes to be made, it says to remove the LEDs and (in essence) R1, R2, R9, and R10. However, it also says, "Moving the RC network on pin 73." Can you clarify what this means? Am I to remove R13? C14? Both? Replace them with something else? Any feedback on this would be appreciated.

**Comment by jdunlap** [comment]
I have got one to work. Yes, you remove R13 and C14.

**Comment by crystalct** [comment]
@jburrell7 Could you tell us if using your ReuPlusC2, does [Sonic Hedgehog the for C64](https://csdb.dk/release/?id=212190) work?

**Comment by jburrell7** [comment]
Crystalct,
I do not know. I am not a gamer and have not tried the interface for gaming. If the Sonic game will run with a standard REU it should also run with this design.

**Comment by jdunlap** [comment]
@crystalct, I can confirm that yes, Sonic the Hedgehog does work with my ReuPlusC2. Jeff did some great work in this design with compatibility to existing REUs!

**Comment by crystalct** [comment]
Now it should be nice to search if all its components are easy to buy and to calculate the price to build one of it.
I will do it...

**Comment by jburrell7** [comment]
The components should be readily available including the FPGA board. The chip shortage is biting the hobbyist community hard. I usually order from Digikey or Mouser as they are good sources for hobbyists - they are more expensive than Ali Express but I don't need to worry about counterfeit components.

If you have trouble obtaining components, send me an email and I can advise on suitable alternatives. Things like capacitors and resistors are commodity components so you can substitute whatever is in the correct package and of the correct value. Ensure the voltage ratings of the capacitors are at least 10V for this design - 25V would be better.

Also note that people have had difficulties building the interface. I am not sure what the problem is, but ensure that the modifications to the FPGA board are carried out as I describe in the video. Also do a visual inspection of the FPGA board to ensure it looks well assembled. I purchased several of these boards and was not too impressed with the build quality.

Feel free to email me if you have any problems.

Jeff

**Comment by crystalct** [comment]
Thanks @jburrell7 
I will try to make an order on JLCPCB with as many smd parts as possible already soldered (microscopic resistors and capacitors are a pain for me).
To contact you via Email, i need your. My is crystal [AT] unict.it

Best regards

**Comment by jburrell7** [comment]
Crystalct,
I understand about the surface mount. Because of my last position I set up a home bench with a binocular microscope that allows me to do assembly with exposed lead SMC. I do limit the size to 0603 and 0.5mm components, though.

I would be interested in how much JLCPCB costs for the PCBs.

Jeff

**Comment by jdunlap** [comment]
Just for a comparison, I ordered from PCBWay a few months ago and got 5 boards with assembly. The assembly and components for the five boards was $231. The production of the five boards was $104. I have three boards completely assembled. I had top add the header for the power pins myself as they are not named on the board, and I did not realize this until I received them. No problem, though, as they are through-hole. I have found that the worst part is finding good FPGA boards. I have several that fail to program or some that program but will not verify. I plan to put the extras on ebay later to recoup my cost. First, though, I have been working on writing a test program that will test the full range of the RAM instead of just what old REUs could have.

**Comment by jburrell7** [comment]
Thanks for the info on PCBWay. I was wondering about assembly costs.
I was (and am) not too impressed by the build quality of the FPGA boards from RioRand and was thinking of spinning a roughly compatible one using an EP4CE6 FPGA. The chip shortage has made that impossible.

Jeff

**Comment by jdunlap** [comment]
Yeah, I had thought about making my own as well. I have enough of them
around now that I could just pull the FPGA off of the original board.
However, I do NOT know enough about FPGAs and the circuits that they need
to really get started. I have designed several of my own PCBs, but nothing
like that.

**Comment by crystalct** [comment]
@jburrell7 
Could you confirm that it is a 4 layers project and not a 2 layers?

**Comment by crystalct** [comment]
4 layers projects aren't economic to print (on JLCPCB).
Anyway using JLCPCB gerber viewer, layers SIGNAL (inner1) and SIGNAL (inner2) haven't connections... 
Is it correct?

**Comment by crystalct** [comment]
Installed CircuitStudio.... it's a 4 layers project because internal layers are GND and VCC (power).
I think it was impossible make a 2 layer project.....

**Comment by jburrell7** [comment]
I have designed many PCBs and designing for hobbyist FPGAs is not that difficult because they are not high performance. The problem is actually getting the parts.

**Comment by jburrell7** [comment]
Yes, this is a 4 layer PCB. The inner layers are power and ground planes. Four layer boards are more expensive but they provide very good signal integrity. I also did not want to be troubleshooting PCB issues along with everything else so I opted for easy.

You can get an open source gerber viewer at:
https://sourceforge.net/projects/gerbv/
This will allow you to see the layers as they are in the board.

Jeff

**Comment by crystalct** [comment]
5 base PCB with those components soldered (only on top layer):
```
C16
C15
U12
R126
R125
J1
C18
C14
U11
C13
U2
U9
U8
U6
R8
R7
U10
R5
R1
C8
C7
C6
C5
C4
C3
R6
R2
C12
C11
C10
C9
R15
R4
R3
C1
C2
U7
C17
```
116 $

There aren't  CMPD6001S TR and 4816P-1-220LF because not available on JLCPCB
There isn't the cliclone board.
There aren't BC501SM-TR and DS3231SN because there aren't strictly necessary.

Too expensive .....
If Ultimate-II+ where available, it would be a much simpler way. 
:-( :-( :-(






























































``

**Comment by jburrell7** [comment]
This board has components that are not required for basic REU functionality.

The 4816P-1-220LF are source damping resistors that are intended to prevent reflections on the C64 bus lines. They are not strictly necessary and you could use any value less than about 25 ohms or simply jumper across the pad on the PCB.

U5, U3, U14, BT1, and J1 can all be eliminated from the build since they do not affect the REU functionality. Unfortunately, the bus buffers are required since they convert the +5V C64 bus to/from the +3.3V I/O voltages from the FPGA.

I agree that the cost of this project is fairly high, but I am not really sure how decrease it for low volume production.
