### ISSUE TITLE
BOM/CPL for JLCPCB

### ISSUE THREAD

**Issue by tRAcE64** [jburrell7/REUPlusC2#2]
Hi,

I'm in the process of getting some of these awesome REU replacements made.
I saw you included a BOM file but JLCPCB does reject it, apparently because it is missing the "Footprint" column.

https://support.jlcpcb.com/article/80-bill-of-materialsbom-file-for-smt-assembly

As I don't have access to Circuit Studio to export these files, is it possible that you can add them for ordering at JLCPCB?

Thanks in advance and if you still need PAL testers, let me know :)

**Comment by jburrell7** [comment]
tRAcE64,
I have uploaded a BOM file to GitHub with the footprint information included.
* I added the connectors for the FPGA board since they were not included in the original BOM.
* The SD Card socket in the original BOM is no longer manufactured so I also included what cross referenced as a substitute.
* The battery holder is its own footprint so ordering it by manufacturer's part number will ensure it is correct.
* I have found the 10uF capacitors are in and out of stock so much that I did not include part numbers. Any capacitor with the correct specification will work.
* I included an "Alternates OK" column for any component that can be freely replaced with any item with the same specifications.
* The RTC (U5), EEPROM (U12) and SD card (J1) are not required for REU functionality so they can be left off of the board to save some cost.
I hope this helps

Jeff

**Comment by tRAcE64** [comment]
Perfect Jeff, thanks for the quick response and the updated BOM file.  This resolves my issue just fine. 
Any idea about the CPL placement file? I can generate it from the PCB layout file manually I think but that would save me some hassle.

tRAcE64

**Comment by jburrell7** [comment]
Are you looking for an automated pick and place file?

Jeff

**Comment by tRAcE64** [comment]
Yes I think that's what I mean. Sorry for misunderstandings, this would be the first time I try to let them handle the assembly.

See: https://support.jlcpcb.com/article/79-pick-place-file-for-smt-assembly

tRAcE64

**Comment by tRAcE64** [comment]
I found out how to do this export with the evaluation edition of Circuit Studio, nevertheless, thanks for your help :+1:
